name: Hello World
author: Koti Buchepalli
description: This is hello world github custom action
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Koti
outputs:
  time:
    description: "The greeting time"
runs:
  using: "node12"
  main: "dist/index.js"