name: CI

on: 
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with: 
          node-version: "17.x"
      - run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage
        env: 
          CI: true
      - name: Build project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy staging
        if: github.event_name == 'push'
        run: echo "npx surge --project ./build --domain silent-apparatus.surge.sh"
        env:
          SURGE_LOGIN: dummylogin
          SURGE_TOKEN: dummytoken


