name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - replace

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: conditional
        run: |
          if [[ ${{ github.event_name }} == 'push' ]] 
          then
            pwd
            touch src/settings.js
            echo ${{ github.event_name }} >> src/settings.js
            cat settings.js
          else
            echo "false"
          fi
        

