name: 'Open Github Issue'
author: Koti 
description: 'Opens a github issue'

inputs:
  token:
    description: 'Github token'
    required: true
  title:
    description: 'Issue title'
    required: true
  body:
    description: 'Issue body'
  assignees:
    description: 'Issue assinees'

outputs:
  issue:
    description: 'The issue object as a json string'
runs: 
  using: "node12"
  main: "dist/index.js"